### ISSUE TITLE
Enforcing date constraints

### ISSUE THREAD

**Issue by MiltosD** [ODRE-Framework/odre-python#1]
If a policy defines the following
```json
"constraint": [{
           "leftOperand": "dateTime",
           "operator": "lteq",
           "rightOperand":  { "@value": "2024-06-11", "@type": "xsd:date" }
       }]
```
if i'm not wrong, one would expect it to be true if the enforcement occurred **_during_** 2024-06-11. However, this does not happen, because  

```python
cast_date("2024-06-11")
```
returns 

```python
datetime.datetime(2024, 6, 11, 0, 0)
```  

which is actually the beginning of the day.

So the above constraint ends up meaning  _"up until the end of 2024-05-11"_, which voids the **"eq"** part... Is this correct;

**Comment by AndreaCimminoArriaga** [comment]
Thanks for your issue and sorry for the late reply, we fixed the code in the last commit.

**Comment by AndreaCimminoArriaga** [comment]
We add a test suite for the issues and [we included yours](https://github.com/ODRE-Framework/odre-python/blob/main/test/test_odre_issues.py). [Version 1.0.5](https://pypi.org/project/pyodre/) adds the necessary code to fix the issue reported. Many thanks
